# 1. This tells docker to use the Rust official image
FROM redis:7.0.1

# 2. Copy the files in your machine to the Docker image

# Build your program for release
# RUN cargo build --release --bin muko_bank

# # Run the binary
# CMD ["./target/release/bank_client"]
